### ISSUE TITLE
composer.json is missing

### ISSUE THREAD

**Issue by mrraghur** [wealthbot-io/core#16]
During setup, where do I get composer.json from?

mylogin@vanavil:/var/www/wealthbot/core/app/config$ php composer.phar install
Composer could not find a composer.json file in /var/www/wealthbot/core/app/config
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by mrraghur** [comment]
Sorry.I messed up some dependencies. I will recheck and post it again, if required.

**Comment by vlad-ko** [comment]
no problem. if you run into any issues, please let us know, there are still things that we need to touch up, since the project is pretty new... so all input is greatly welcomed.
