### ISSUE TITLE
Disable default vhosts

### ISSUE THREAD

**Issue by gkobilansky** [wealthbot-io/core#29]
lrwxrwxrwx 1 root root 54 May 20 16:54 10-default_vhost_443.conf -> /etc/apache2/sites-available/10-default_vhost_443.conf
lrwxrwxrwx 1 root root 53 May 20 16:54 10-default_vhost_80.conf -> /etc/apache2/sites-available/10-default_vhost_80.conf

**Comment by vlad-ko** [comment]
this was fixed. need to test.
