### ISSUE TITLE
sudo apt-get php5-mongo

### ISSUE THREAD

**Issue by mrraghur** [wealthbot-io/core#30]
In installation instructions, 

you typed 
sudo apt-get php5-mongo

You probably meant sudo apt-get <b>install</b> php5-mongo

Btw, what repository are you using to get php5-mongo?

For me the command returns 
E: Unable to locate package php5-mongo

Thanks

**Comment by mrraghur** [comment]
This command can be replaced by 

pecl install mongo

Also, 
It looks like composer.phar file has been removed during latest checkins

**Comment by vlad-ko** [comment]
@mrraghur, thanks for your feedback. readme needs to be updated, but basically you need to install mongo and php/mongo driver. i am provisioning vagrant to allow for quick spin up of local env.

you can test drive it by doing: 
cd vagrant 
vagrant up

you'll need to map your /etc/hosts to a local "vagrant" ip 192.168.56.103 ... see vagrant/puphpet/config.yaml

**Comment by vlad-ko** [comment]
this will be fixed with #28 and #29
